name: meu_app_sqflite
description: Um projeto Flutter para gerenciar itens com SQFlite e sincronização.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.0.11
  path: ^1.8.3
  http: ^1.1.0 # Para requisições HTTP
  connectivity_plus: ^5.0.1 # Para verificar a conexão com a internet
  firebase_core: ^2.24.2 # Para setup inicial do Firebase
  firebase_crashlytics: ^3.4.9 # Para tratamento de erros em produção

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true